---
- name: Create a backup directory if it doesn't exist
  file:
    path: "/home/ubuntu/backups"
    state: directory
    mode: '0755'

- name: Save Redis state to a dump file
  command: redis-cli save
  register: redis_save_result
  ignore_errors: yes

- name: Copy Redis dump file to backup directory
  copy:
    src: "/var/lib/redis/dump.rdb"
    dest: "/home/ubuntu/backups/dump_{{ ansible_date_time.date }}.rdb"
  when: redis_save_result is succeeded

- name: Create a tarball of application data and configurations
  command: tar czf "/home/ubuntu/backups/urless_{{ ansible_date_time.date }}.tar.gz" \
    -C "{{ deployment_path }}" . \
    --transform="s,^,/configs/," -C "/path/to/configs" .
  register: backup_result
  ignore_errors: yes

- name: Remove oldest backups if exceeding rollback limit
  shell: "ls -1t /home/ubuntu/backups/*.tar.gz | tail -n +{{ rollback_limit + 1 }} | xargs rm -f"
  when: backup_result is succeeded

